---
  name: Hello-C-World 
  build: pdf
  cover1: pic/tinylab.org-sina-weibo.jpg
  cover_desc1: 扫一扫，关注 @泰晓科技 新浪微博
  cover2: pic/tinylab.org-weixin-logo.jpg
  cover_desc2: 扫一扫，关注 @泰晓科技 微信公众号
  lang: zh
  license: ccbyncnd30
  config: config/main.yml
  template: latex/template.tex
  preface-files: preface/*.markdown
  chapter-files: chapters/*.markdown
  appendix-files: appendix/*.markdown 
